% Probabilidades das doenças.
probabilidade(covid19, 0.1).
probabilidade(gripe, 0.2).
probabilidade(dengue, 0.15).
probabilidade(asthma, 0.05).
probabilidade(diabetes, 0.08).
probabilidade(hipertensao, 0.12).
probabilidade(anemia, 0.07).
probabilidade(obesidade, 0.09).
probabilidade(depressao, 0.11).
probabilidade(ansiedade, 0.13).
probabilidade(hipotireoidismo, 0.06).
probabilidade(hipertireoidismo, 0.04).
probabilidade(insuficiencia_renal, 0.03).
probabilidade(hepatite, 0.02).
probabilidade(pneumonia, 0.05).
probabilidade(tuberculose, 0.03).
probabilidade(gastrite, 0.07).
probabilidade(ulcera_peptica, 0.06).
probabilidade(artrite_reumatoide, 0.04).
probabilidade(osteoporose, 0.03).
